import type { Metadata } from "next";
import { Gantari } from "next/font/google";
import Provider from "./_trpc/Provider";
import "./globals.css";

const gantari = Gantari({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${gantari.className}`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
